name: Auto Commit

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important: fetch all history to allow git pull

      - name: Make your changes
        run: |
          echo "Generated" >> example.txt
          git add .
          git commit -m "generated" || echo "No changes to commit"

      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Pull latest changes before push
        run: |
          git pull --rebase origin main

      - name: Push changes
        run: |
          git push origin main
