name: Generate Pac-Man Game

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Move output to .github/pacman-graph
        run: |
          mkdir -p .github/pacman-graph
          mv dist/*.svg .github/pacman-graph/

      - name: Commit and Push Changes
        run: |
          git add .github/pacman-graph
          git commit -m "Update Pac-Man contribution graph [skip ci]" || echo "No changes to commit"
          git push origin main
